image: jsyeo/chocolatey

variables:
  CHOCO_OPTS: "--allow-unofficial"

deploy:
  stage: deploy
  before_script:
    - choco $CHOCO_OPTS pack
    - ls -lash
    - choco $CHOCO_OPTS apikey --key $CHOCO_API_KEY --source https://push.chocolatey.org/
  script:
    - choco $CHOCO_OPTS push srcclr.*.nupkg --source https://push.chocolatey.org/
  only:
    - master
  when: manual
