image: jsyeo/chocolatey

deploy:
  stage: deploy
  before_script:
    - choco pack
    - ls -lash
    - choco apikey --key $CHOCO_API_KEY --source https://push.chocolatey.org/
  script:
    - choco push srcclr.*.nupkg --source https://push.chocolatey.org/
  only:
    - master
  when: manual
